### PR TITLE
Bug/#60 fixing lire flow bugs

### LINKED ISSUE #60: Fixing LireFlow bugs
**Descrição**

Atualmente, durante a leitura sequencial no LireFlow, o destaque das palavras está apresentando um comportamento incorreto:  o destaque “salta” linhas, em vez de seguir o fluxo natural do texto. Esse comportamento causa confusão visual e prejudica a fluência da leitura.

Comportamento esperado:
O destaque deve percorrer as palavras na ordem natural do texto. O efeito de destaque deve continuar de forma suave, sem pular linhas ou causar deslocamentos bruscos.

### PR DESCRIPTION
**Pull request by anajufg**
## 📝 Description

To fix the bug that occurred mainly on smaller screens, a more robust flow-control system was implemented to prevent re-renders from interrupting the animation and breaking the activity. This mechanism ensures that previous flows don’t wait on unnecessary awaits and eliminates the paragraph-jumping behavior that was disrupting continuous reading.

Additionally, the user experience in LireFlow was improved on mobile devices through the introduction of automatic scrolling, ensuring better visual tracking of highlighted words. Performance optimizations were also applied to the codebase, resulting in smoother and more stable overall behavior.

## 🔗 Related Issue

Closes #60

## ✅ Checklist

Please make sure you have completed all of the following items before submitting this PR:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have created a constants file, or added the constants to their proper locations.
- [x] I have created a hook to contain non-UI logic.
- [ ] I have performed a pair review.

### CODE REVIEW

File: src/features/lireFlow/hooks/useWordHighlighter.ts [hunk 1]
```diff
@@ -1,119 +1,213 @@
...
+
+      if (isNotActiveFlow(flowId)) return;
+
+      indexRef.current++;
+    }
+
+    setCurrentIndex(null);
+
+    if (onFinish) {
+      if (isNotActiveFlow(flowId)) return;
```
Comment (RamiroNoronha) [inline src/features/lireFlow/hooks/useWordHighlighter.ts]: try to avoid nested ifs

File: src/features/lireFlow/hooks/useWordHighlighter.ts [hunk 2]
```diff
@@ -1,119 +1,213 @@
...
+    );
+  };
+
+  const isNotActiveFlow = (flowId: number): boolean => {
+    return activeFlowIdRef.current !== flowId;
+  };
+
+  const highlightFlow = async (flowId: number): Promise<void> => {
+    while (indexRef.current < elementIndexs.current.length) {
+      if (!isReadingRef.current || isNotActiveFlow(flowId)) return;
```
Comment (RamiroNoronha) [inline src/features/lireFlow/hooks/useWordHighlighter.ts]: Try to put the if logic in a meaning variable 
```suggestion
      const meaningVariableName = !isReadingRef.current || isNotActiveFlow(flowId);
      
      if (meaningVariableName ) return;
```

File: src/features/lireFlow/hooks/useWordHighlighter.ts [hunk 3]
```diff
@@ -1,119 +1,213 @@
...
+    speedRef.current,
+  ]);
 
   const scrollToCurrentWord = useCallback(() => {
-    if (currentWordRef.current) {
-      currentWordRef.current.scrollIntoView({
+    const word = currentWordRef.current;
+    const container = containerRef.current;
+
+    if (!word || !container || !('IntersectionObserver' in window)) return;
```
Comment (RamiroNoronha) [inline src/features/lireFlow/hooks/useWordHighlighter.ts]: Create a meaning variable here

**Review by RamiroNoronha — APPROVED** [review]
